version: '3.8'
services:
  app:
    container_name: billingsystem
    build: ./
    ports:
      - "8091:8091"
    depends_on:
      - dbpostgresql

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:6000/billingsystem
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=blessed!@#
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  dbpostgresql:
    image: postgres
    ports:
      - "6000:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=blessed!@#
      - POSTGRES_USER=postgres
      - POSTGRES_DB=billingsystem
