version: '3.8'
services:
  app:
    container_name: billingsystem
    build: ./
    ports:
      - "8091:8091"
    links:
     - dbpostgresql
    depends_on:
      - dbpostgresql
      - elasticsearch
    env_file:
      - .env
  dbpostgresql:
    image: postgres
    ports:
      - "5435:5432"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
     - ./postgres-data:/var/lib/postgresql/data

  elasticsearch:
    image: elasticsearch:7.17.6
    restart: always
    ports:
       - "9200:9200"
       - "9300:9300"
    environment:
       - bootstrap.memory_lock=true
       - cluster.name= BillingElastic
       - discovery.type=single-node
       - http.host=0.0.0.0
       - transport.host=127.0.0.1
       - xpack.security.enabled=false
       - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
       soft: -1
       hard: -1
    user: elasticsearch
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 15
  kibana:
    image: kibana:7.17.6
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch