
version: '3.8'
services:
  app:
    container_name: billingsystem
    build: ./
    ports:
      - "8091:8091"
    links:
     - dbpostgresql
    depends_on:
      - dbpostgresql

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5435/db-billing
      - SPRING_DATASOURCE_USERNAME=blessed
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create

  dbpostgresql:
    image: postgres
    ports:
      - "5435:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=blessed
      - POSTGRES_DB=db-billing