version: '3.8'
services:
  app:
    container_name: billingsystem
    build: ./
    ports:
      - "8091:8091"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - billing-network


  db:
    image: postgres:15rc2-alpine3.16
    ports:
      - "5435:5432"
    restart: always
    env_file:
      - .env
    volumes:
     - ./postgres-data:/var/lib/postgresql/data
     - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
    - billing-network


  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/prometheus.yaml
      - ./prometheus_data:/prometheus
    command:
        - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana-oss:8.5.2
    pull_policy: always
    #network_mode: host
    container_name: grafana
    restart: unless-stopped
    user: "472"
    ports:
      - "3000:3000"
    links:
      - prometheus:prometheus
    volumes:
      - ./grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_DOMAIN=localhost

networks:
   billing-network: