version: '3.8'
services:
  app:
    container_name: billingsystem
    build: ./
    ports:
      - "8091:8091"
    links:
     - dbpostgresql
    depends_on:
      - dbpostgresql
    env_file:
      - .env
  dbpostgresql:
    image: postgres
    ports:
      - "5435:5432"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
     - ./postgres-data:/var/lib/postgresql/data